apiVersion: v2
name: spar-g2pconnect-id-mapper
description: A Helm chart for SPAR G2P Connect ID Mapper
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
