apiVersion: v1
kind: Service
metadata:
  name: {{ include "sparMapperfullname" . }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /mapper/v1/ping
  labels:
    {{- include "sparMapperlabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sparMapperselectorLabels" . | nindent 4 }}
