apiVersion: v2
name: sunbird-rc-core
description: A Helm chart for Sunbird Registry
type: application
version: 0.1.0
appVersion: "v0.0.14"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
- name: elasticsearch
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.x.x
  condition: elasticsearch.enabled
