apiVersion: v1
entries:
  spar-helm-chart:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-03-07T07:54:10.463479543Z"
    dependencies:
    - name: social-payments-account-registry
      repository: ""
      version: 0.1.0
    - name: spar-self-service-ui
      repository: ""
      version: 0.1.0
    description: A Helm chart for spar application
    digest: 7a2dfd06a0f659974db07655bb6d03f471822aa0d7d547562fd228483f6bfc5b
    name: spar-helm-chart
    urls:
    - spar-helm-chart-0.1.0.tgz
    version: 0.1.0
generated: "2024-03-07T07:54:10.418935467Z"
