apiVersion: v1
kind: Service
metadata:
  name: {{ include "spar.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /spar/v1/ping
  labels:
    {{- include "spar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spar.selectorLabels" . | nindent 4 }}
